version: '3.1'

services:
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - reverse-proxy-net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent.reverse-proxy-net:9001 --tlsskipverify
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:portainer.localhost
      - traefik.port=9000
      - traefik.docker.network=reverse-proxy-net
    networks:
      - reverse-proxy-net
    ports:
      - 9000:9000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  reverse-proxy-net:
   external:
    name: reverse-proxy-net

volumes:
  portainer_data:
